FROM docker.io/jerrea2/kollective-vto:gpu-v4.2
WORKDIR /app
COPY inference.py /app/inference.py
EXPOSE 80
CMD ["python","-m","uvicorn","inference:app","--host","0.0.0.0","--port","80","--log-level","debug"]