FROM pytorch/pytorch:2.3.1-cuda12.1-cudnn8-runtime

ENV PYTHONUNBUFFERED=1 `
    PIP_NO_CACHE_DIR=1 `
    PYTHONPATH=/app

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN python -m pip install --upgrade pip && `
    pip install --no-cache-dir -r /app/requirements.txt

COPY src /app/src
